---
- hosts: test-runner
  tasks:
    - name: Ensure the artifacts directory exists
      file:
        path: '{{ lookup("env", "PWD") }}/artifacts'
        state: directory
      delegate_to: localhost

    - name: Retrieve junit results
      ignore_errors: true
      fetch:
        src: ~/tower-qa/reports/junit/results-collection.xml
        dest: '{{ lookup("env", "PWD") }}/artifacts/results-collection.xml'
        flat: true
