---

create_ec2_assign_public_ip: true
create_ec2_vpc_id: vpc-552da032
create_ec2_vpc_subnet_id: subnet-9cdddbb0

user_data_install_py2: &install_py2
  "{{ lookup('file', 'files/install_py2.sh') }}"

ec2_images:
  - {'name': 'centos-7.latest-x86_64', 'user': 'centos', 'id': 'ami-9887c6e7', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower'}
  - {'name': 'rhel-7.4-x86_64', 'user': 'ec2-user', 'id': 'ami-7a96b801', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower'}
  - {'name': 'rhel-7.5-x86_64', 'user': 'ec2-user', 'id': 'ami-0d70a070', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower'}
  - {'name': 'rhel-7.6-x86_64', 'user': 'ec2-user', 'id': 'ami-06fd194eff2ab1451', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower'}
  - {'name': 'rhel-7.7-x86_64', 'user': 'ec2-user', 'id': 'ami-00936483548a6d57f', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower'}
  - {'name': 'rhel-8.0-x86_64', 'user': 'ec2-user', 'id': 'ami-098bb5d92c8886ca1', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower'}
  - {'name': 'rhel-8.1-x86_64', 'user': 'ec2-user', 'id': 'ami-002cdac160d085b42', 'type': 'm5.large', 'groups': 'tower,instance_group_non_default', 'security_group': 'Tower'}

ec2_security_groups:
  - name: Tower
    description: Security group for Tower instances
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 5432
        to_port: 5432
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: udp
        from_port: 9001
        to_port: 9001
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 9001
        to_port: 9001
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
