# This manifest stores the secret key used for authenticating with AWS
# The purpose of this is so that the cert-manager can authenticate with route53 to validate domain ownership
apiVersion: v1
kind: Secret
metadata:
  name: prod-route53-credentials-secret
type: Opaque
data:
  #replace with actual key
  secret-access-key: '$AWX_ACCESS_KEY_base64_encoded'
