# This requires cert-manager to be installed in the cluster.
# This is a certificate definition. It will allow cert-manager to periodically renew the wildcard cert consumed by nginx-app-proxy.
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
 name: tower-qe-services-tls
 namespace: default
spec:
 secretName: tower-qe-tls
 issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer
 dnsNames:
   - '*.services.k8s.tower-qe.testing.ansible.com'
 acme:
   config:
     - dns01:
         provider: route53
       domains:
         - '*.services.k8s.tower-qe.testing.ansible.com'
