# This requires cert-manager to be installed in the cluster.
# This is a certificate definition. It will allow cert-manager to periodically renew the wildcard cert consumed by nginx-app-proxy.
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
 name: tower-qe-services-tls
 namespace: default
spec:
 secretName: tower-qe-tls
 duration: 2160h
 renewBefore: 360h
 organization:
   - jetstack
 usages:
   - server auth
   - client auth
 issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer
 dnsNames:
   - '*.services.k8s.tower-qe.testing.ansible.com'
